# Build and publish package when release is created.

name: Publish Release

on:
  release:
    types: [created]

env:
  JAVA_VERSION_TO_USE: '11'
  JAVA_DISTRI_TO_USE: 'corretto'
  GITHUB_TOKEN_READ_PACKAGES: ${{ secrets.GH_WORKFLOWS_PAT_READ_PACKAGES }}
  GITHUB_TOKEN_DEPLOY_PACKAGES: ${{ github.token }}
  DEPLOY_RETRY: 10

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK ${{ env.JAVA_VERSION_TO_USE }} (${{ env.JAVA_DISTRI_TO_USE }}) for build
      uses: actions/setup-java@v3
      with:
        java-version: ${{ env.JAVA_VERSION_TO_USE }}
        distribution: ${{ env.JAVA_DISTRI_TO_USE }}
        cache: maven

    - name: Configure maven settings.xml
      uses: whelk-io/maven-settings-xml-action@v20
      with:
        repositories: '[{ "id": "github-pkgs", "url": "https://maven.pkg.github.com/arvato-systems-jacs/dummy", "snapshots": { "enabled": "true" } }]'          
        plugin_repositories: '[{ "id": "github-pkgs", "url": "https://maven.pkg.github.com/arvato-systems-jacs/dummy", "snapshots": { "enabled": "true" } }]'
        servers: |
          [
            { "id": "github-pkgs", "username": "dummy", "password": "${env.GITHUB_TOKEN_READ_PACKAGES}" },
            { "id": "github", "username": "${env.GITHUB_ACTOR}", "password": "${env.GITHUB_TOKEN_DEPLOY_PACKAGES}" }
          ]

    - name: Update parent to latest version
      run: mvn -B versions:update-parent

    - name: Remove snapshot version
      run: mvn -B versions:set -DremoveSnapshot

    - name: Use releases in dependencies
      run: mvn -B versions:use-releases

    - name: Build and Publish
      run: mvn -B -Pgithub -DskipTests -DdeployAtEnd=true -DretryFailedDeploymentCount=${{ env.DEPLOY_RETRY }} deploy
